// AUTO-GENERATED by scripts/fetch-car-images.mjs — do not edit by hand.
// Photos come from Wikipedia/Wikimedia Commons and stay under their original
// licences; each entry carries its source page and attribution.
import type { CarImage } from "@/lib/types";

export const CAR_IMAGES: Record<string, CarImage> = {
  "fiat-egea": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/fiat-egea/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/fiat-egea/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQID/8QAIhAAAQQBAgcAAAAAAAAAAAAAAQACAwQRBRIhIjM0QmFy/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABYRAQEBAAAAAAAAAAAAAAAAAAARIf/aAAwDAQACEQMRAD8Aymsyx2+eDLC7AbsG0j0qdboyOAirNMhHjwykbPbTfKA03rtSk1//2Q==",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_Tipo_(2015)",
      "sourcePageTitle": "Fiat Tipo (2015)",
      "artist": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-clio": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/renault-clio/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/renault-clio/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAIBAAAgEDBAMAAAAAAAAAAAAAAQIDAAQRISIzcTEykf/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFxEAAwEAAAAAAAAAAAAAAAAAAAEREv/aAAwDAQACEQMRAD8AzwLZDkRmkAOumD0Kt5bVo2CKSfC42kfKLn9j3SFvxrU6iGH/2Q==",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Clio",
      "sourcePageTitle": "Renault Clio",
      "artist": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "toyota-corolla": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/toyota-corolla/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/toyota-corolla/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwIF/8QAIxAAAgECBAcAAAAAAAAAAAAAAQMCAAQFETNxEhMhMUFRYf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAVEQEBAAAAAAAAAAAAAAAAAAAAEf/aAAwDAQACEQMRAD8Add5YqVFoZKAOQkvMEjx2NFiT7AT5Yk5dwB0krhI+Z+6nFdE7ViWmrHelI//Z",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Corolla",
      "sourcePageTitle": "Toyota Corolla",
      "artist": "Alexander Migl",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "dacia-duster": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/dacia-duster/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/dacia-duster/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBf/EAB8QAAEEAgIDAAAAAAAAAAAAAAECAwQRABIhMjOBwf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAARAAH/2gAMAwEAAhEDEQA/AM9M2HHdIcZtaRVqUefWCZSJJ2DC9iaqzqkfTiJHkyxnqnAmSL//2Q==",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Duster",
      "sourcePageTitle": "Dacia Duster",
      "artist": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "volkswagen-passat": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/volkswagen-passat/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/volkswagen-passat/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAIBAAAgICAQUBAAAAAAAAAAAAAQIDBAARcQUSMzSRof/EABQBAQAAAAAAAAAAAAAAAAAAAAH/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/AM9Wt0xwEDzO6jbHfaB+ZS2qIhLQpKxOwIid/dDA5/K/OMUvXXjBckNv/9k=",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Passat",
      "sourcePageTitle": "Volkswagen Passat",
      "artist": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "renault-megane": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/renault-megane/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/renault-megane/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwQF/8QAIhAAAgEDAgcAAAAAAAAAAAAAAQIAAwQhERIiMjNBcZGh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAVEQEBAAAAAAAAAAAAAAAAAAAAMf/aAAwDAQACEQMRAD8AhpPY0tHQbSM7cE/e8Wu9iyAqSGOOEj2RCuumJmU+ceYqx//Z",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_M%C3%A9gane",
      "sourcePageTitle": "Renault Mégane",
      "artist": "Vauxford",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-i20": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/hyundai-i20/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/hyundai-i20/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwX/xAAhEAACAQMDBQAAAAAAAAAAAAABAgMABBESEyExNGGB0f/EABUBAQEAAAAAAAAAAAAAAAAAAAEC/8QAFxEBAAMAAAAAAAAAAAAAAAAAAAECEf/aAAwDAQACEQMRAD8AHdspA8u5KrE5OFB58UbXsboVOqUEcLn5Uxu791Vg6VFtgv/Z",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_i20",
      "sourcePageTitle": "Hyundai i20",
      "artist": "© M 93",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "fiat-doblo": {
      "wide": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/fiat-doblo/wide.jpg",
      "square": "https://mmszczivilqeqvyrlnqg.supabase.co/storage/v1/object/public/car-photos/fiat-doblo/square.jpg",
      "width": 1280,
      "height": 720,
      "blurDataURL": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAJABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwEC/8QAIBAAAgICAAcAAAAAAAAAAAAAAQIAEQMEBRITITFRgf/EABUBAQEAAAAAAAAAAAAAAAAAAAAC/8QAFhEBAQEAAAAAAAAAAAAAAAAAABFB/9oADAMBAAIRAxEAPwAG4sEL4g7IPd9zMYdosW6geuU0xNG5Njz8gZpWQf/Z",
      "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_Dobl%C3%B2",
      "sourcePageTitle": "Fiat Doblò",
      "artist": "TuRbO_J from Adelaide, Australia",
      "license": "CC BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
};
