// AUTO-GENERATED by scripts/fetch-car-images.mjs — do not edit by hand.
// Photos are sourced from Wikipedia/Wikimedia Commons and remain under
// their original licenses; see each entry's sourcePageUrl for attribution.
import type { CarImage } from "@/lib/types";

export const CAR_IMAGES: Record<string, CarImage> = {
  "fiat-egea": {
    "src": "/car-photos/fiat-egea.jpg",
    "width": 640,
    "height": 358,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_Tipo_(2015)",
    "sourcePageTitle": "Fiat Tipo (2015)",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-clio": {
    "src": "/car-photos/renault-clio.jpg",
    "width": 640,
    "height": 364,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Clio",
    "sourcePageTitle": "Renault Clio",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "toyota-corolla": {
    "src": "/car-photos/toyota-corolla.jpg",
    "width": 640,
    "height": 323,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Corolla",
    "sourcePageTitle": "Toyota Corolla",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "dacia-duster": {
    "src": "/car-photos/dacia-duster.jpg",
    "width": 640,
    "height": 387,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Duster",
    "sourcePageTitle": "Dacia Duster",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "volkswagen-passat": {
    "src": "/car-photos/volkswagen-passat.jpg",
    "width": 640,
    "height": 322,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Passat",
    "sourcePageTitle": "Volkswagen Passat",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "renault-megane": {
    "src": "/car-photos/renault-megane.jpg",
    "width": 640,
    "height": 315,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_M%C3%A9gane",
    "sourcePageTitle": "Renault Mégane",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-i20": {
    "src": "/car-photos/hyundai-i20.jpg",
    "width": 640,
    "height": 321,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_i20",
    "sourcePageTitle": "Hyundai i20",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "fiat-doblo": {
    "src": "/car-photos/fiat-doblo.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_Dobl%C3%B2",
    "sourcePageTitle": "Fiat Doblò",
    "artist": "TuRbO_J from Adelaide, Australia",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  "opel-corsa": {
    "src": "/car-photos/opel-corsa.jpg",
    "width": 640,
    "height": 395,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Opel_Corsa",
    "sourcePageTitle": "Opel Corsa",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-c-hr": {
    "src": "/car-photos/toyota-c-hr.jpg",
    "width": 640,
    "height": 372,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_C-HR",
    "sourcePageTitle": "Toyota C-HR",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "honda-civic": {
    "src": "/car-photos/honda-civic.jpg",
    "width": 640,
    "height": 326,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Honda_Civic",
    "sourcePageTitle": "Honda Civic",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "peugeot-208": {
    "src": "/car-photos/peugeot-208.jpg",
    "width": 640,
    "height": 318,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_208",
    "sourcePageTitle": "Peugeot 208",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "peugeot-308": {
    "src": "/car-photos/peugeot-308.jpg",
    "width": 640,
    "height": 343,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_308",
    "sourcePageTitle": "Peugeot 308",
    "artist": "A.BourgeoisP",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "citroen-c3": {
    "src": "/car-photos/citroen-c3.jpg",
    "width": 640,
    "height": 379,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Citro%C3%ABn_C3",
    "sourcePageTitle": "Citroën C3",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "skoda-octavia": {
    "src": "/car-photos/skoda-octavia.jpg",
    "width": 640,
    "height": 339,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Octavia",
    "sourcePageTitle": "Škoda Octavia",
    "artist": "Mike-fiesta",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-golf": {
    "src": "/car-photos/volkswagen-golf.jpg",
    "width": 640,
    "height": 326,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Golf",
    "sourcePageTitle": "Volkswagen Golf",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "nissan-qashqai": {
    "src": "/car-photos/nissan-qashqai.jpg",
    "width": 640,
    "height": 383,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Nissan_Qashqai",
    "sourcePageTitle": "Nissan Qashqai",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-sportage": {
    "src": "/car-photos/kia-sportage.jpg",
    "width": 640,
    "height": 335,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Sportage",
    "sourcePageTitle": "Kia Sportage",
    "artist": "LuvsMG481",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-tucson": {
    "src": "/car-photos/hyundai-tucson.jpg",
    "width": 640,
    "height": 343,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Tucson",
    "sourcePageTitle": "Hyundai Tucson",
    "artist": "SsmIntrigue",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-tiguan": {
    "src": "/car-photos/volkswagen-tiguan.jpg",
    "width": 640,
    "height": 380,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Tiguan",
    "sourcePageTitle": "Volkswagen Tiguan",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "fiat-fiorino": {
    "src": "/car-photos/fiat-fiorino.jpg",
    "width": 640,
    "height": 529,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_Fiorino",
    "sourcePageTitle": "Fiat Fiorino",
    "artist": "M 93",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  "ford-focus": {
    "src": "/car-photos/ford-focus.jpg",
    "width": 640,
    "height": 323,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Focus",
    "sourcePageTitle": "Ford Focus",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "ford-puma": {
    "src": "/car-photos/ford-puma.jpg",
    "width": 640,
    "height": 356,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Puma_(crossover)",
    "sourcePageTitle": "Ford Puma (crossover)",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "suzuki-vitara": {
    "src": "/car-photos/suzuki-vitara.jpg",
    "width": 640,
    "height": 324,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Suzuki_Vitara",
    "sourcePageTitle": "Suzuki Vitara",
    "artist": "EurovisionNim",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "jeep-renegade": {
    "src": "/car-photos/jeep-renegade.jpg",
    "width": 640,
    "height": 364,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Jeep_Renegade",
    "sourcePageTitle": "Jeep Renegade",
    "artist": "M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "jeep-compass": {
    "src": "/car-photos/jeep-compass.jpg",
    "width": 640,
    "height": 365,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Jeep_Compass",
    "sourcePageTitle": "Jeep Compass",
    "artist": "Kevauto",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mini-cooper": {
    "src": "/car-photos/mini-cooper.jpg",
    "width": 640,
    "height": 368,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mini_Cooper",
    "sourcePageTitle": "Mini Cooper",
    "artist": "M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "togg-t10x": {
    "src": "/car-photos/togg-t10x.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Togg_T10X",
    "sourcePageTitle": "Togg T10X",
    "artist": "Metuboy",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "tesla-model-3": {
    "src": "/car-photos/tesla-model-3.jpg",
    "width": 640,
    "height": 426,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Tesla_Model_3",
    "sourcePageTitle": "Tesla Model 3",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "byd-seal": {
    "src": "/car-photos/byd-seal.jpg",
    "width": 640,
    "height": 364,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BYD_Seal",
    "sourcePageTitle": "BYD Seal",
    "artist": "User3204",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mg-zs": {
    "src": "/car-photos/mg-zs.jpg",
    "width": 640,
    "height": 376,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/MG_ZS_(crossover)",
    "sourcePageTitle": "MG ZS (crossover)",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "bmw-3-serisi": {
    "src": "/car-photos/bmw-3-serisi.jpg",
    "width": 640,
    "height": 328,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BMW_3_Series",
    "sourcePageTitle": "BMW 3 Series",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-c-serisi": {
    "src": "/car-photos/mercedes-benz-c-serisi.jpg",
    "width": 640,
    "height": 312,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_C-Class",
    "sourcePageTitle": "Mercedes-Benz C-Class",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-a3": {
    "src": "/car-photos/audi-a3.jpg",
    "width": 640,
    "height": 348,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_A3",
    "sourcePageTitle": "Audi A3",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volvo-xc40": {
    "src": "/car-photos/volvo-xc40.jpg",
    "width": 640,
    "height": 376,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volvo_XC40",
    "sourcePageTitle": "Volvo XC40",
    "artist": "Elise240SX",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "land-rover-defender": {
    "src": "/car-photos/land-rover-defender.jpg",
    "width": 640,
    "height": 428,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Land_Rover_Defender",
    "sourcePageTitle": "Land Rover Defender",
    "artist": "OSX",
    "license": "Public domain",
    "licenseUrl": null
  },
  "porsche-911": {
    "src": "/car-photos/porsche-911.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Porsche_911",
    "sourcePageTitle": "Porsche 911",
    "artist": "Matti Blume",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "ford-mustang": {
    "src": "/car-photos/ford-mustang.jpg",
    "width": 640,
    "height": 337,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Mustang",
    "sourcePageTitle": "Ford Mustang",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-captur": {
    "src": "/car-photos/renault-captur.jpg",
    "width": 640,
    "height": 362,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Captur",
    "sourcePageTitle": "Renault Captur",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "dacia-sandero": {
    "src": "/car-photos/dacia-sandero.jpg",
    "width": 640,
    "height": 428,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Sandero",
    "sourcePageTitle": "Dacia Sandero",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "dacia-jogger": {
    "src": "/car-photos/dacia-jogger.jpg",
    "width": 640,
    "height": 405,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Jogger",
    "sourcePageTitle": "Dacia Jogger",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "fiat-500": {
    "src": "/car-photos/fiat-500.jpg",
    "width": 640,
    "height": 545,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_500",
    "sourcePageTitle": "Fiat 500",
    "artist": "IFCAR",
    "license": "Public domain",
    "licenseUrl": null
  },
  "peugeot-3008": {
    "src": "/car-photos/peugeot-3008.jpg",
    "width": 640,
    "height": 393,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_3008",
    "sourcePageTitle": "Peugeot 3008",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "peugeot-2008": {
    "src": "/car-photos/peugeot-2008.jpg",
    "width": 640,
    "height": 366,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_2008",
    "sourcePageTitle": "Peugeot 2008",
    "artist": "Cutlass",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
  },
  "citroen-c4-cactus": {
    "src": "/car-photos/citroen-c4-cactus.jpg",
    "width": 640,
    "height": 426,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Citro%C3%ABn_C4_Cactus",
    "sourcePageTitle": "Citroën C4 Cactus",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "skoda-fabia": {
    "src": "/car-photos/skoda-fabia.jpg",
    "width": 640,
    "height": 332,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Fabia",
    "sourcePageTitle": "Škoda Fabia",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-bayon": {
    "src": "/car-photos/hyundai-bayon.jpg",
    "width": 640,
    "height": 384,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Bayon",
    "sourcePageTitle": "Hyundai Bayon",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-kona": {
    "src": "/car-photos/hyundai-kona.jpg",
    "width": 640,
    "height": 361,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Kona",
    "sourcePageTitle": "Hyundai Kona",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-stonic": {
    "src": "/car-photos/kia-stonic.jpg",
    "width": 640,
    "height": 325,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Stonic",
    "sourcePageTitle": "Kia Stonic",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-ceed": {
    "src": "/car-photos/kia-ceed.jpg",
    "width": 640,
    "height": 304,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Ceed",
    "sourcePageTitle": "Kia Ceed",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-niro": {
    "src": "/car-photos/kia-niro.jpg",
    "width": 640,
    "height": 379,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Niro",
    "sourcePageTitle": "Kia Niro",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-taliant": {
    "src": "/car-photos/renault-taliant.jpg",
    "width": 640,
    "height": 351,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Logan",
    "sourcePageTitle": "Dacia Logan",
    "artist": "Mihnea Lazăr",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-broadway": {
    "src": "/car-photos/renault-broadway.jpg",
    "width": 640,
    "height": 351,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Logan",
    "sourcePageTitle": "Dacia Logan",
    "artist": "Mihnea Lazăr",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "opel-astra": {
    "src": "/car-photos/opel-astra.jpg",
    "width": 640,
    "height": 325,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Opel_Astra",
    "sourcePageTitle": "Opel Astra",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "opel-mokka": {
    "src": "/car-photos/opel-mokka.jpg",
    "width": 640,
    "height": 374,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Opel_Mokka",
    "sourcePageTitle": "Opel Mokka",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "nissan-juke": {
    "src": "/car-photos/nissan-juke.jpg",
    "width": 640,
    "height": 338,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Nissan_Juke",
    "sourcePageTitle": "Nissan Juke",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-yaris": {
    "src": "/car-photos/toyota-yaris.jpg",
    "width": 640,
    "height": 393,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Yaris",
    "sourcePageTitle": "Toyota Yaris",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-rav4": {
    "src": "/car-photos/toyota-rav4.jpg",
    "width": 640,
    "height": 383,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_RAV4",
    "sourcePageTitle": "Toyota RAV4",
    "artist": "Mr.choppers",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "honda-cr-v": {
    "src": "/car-photos/honda-cr-v.jpg",
    "width": 640,
    "height": 352,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Honda_CR-V",
    "sourcePageTitle": "Honda CR-V",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "mazda-cx-5": {
    "src": "/car-photos/mazda-cx-5.jpg",
    "width": 640,
    "height": 412,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mazda_CX-5",
    "sourcePageTitle": "Mazda CX-5",
    "artist": "Mr.choppers",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  "subaru-forester": {
    "src": "/car-photos/subaru-forester.jpg",
    "width": 640,
    "height": 368,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Subaru_Forester",
    "sourcePageTitle": "Subaru Forester",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-t-roc": {
    "src": "/car-photos/volkswagen-t-roc.jpg",
    "width": 640,
    "height": 344,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_T-Roc",
    "sourcePageTitle": "Volkswagen T-Roc",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "volkswagen-polo": {
    "src": "/car-photos/volkswagen-polo.jpg",
    "width": 640,
    "height": 353,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Polo",
    "sourcePageTitle": "Volkswagen Polo",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "seat-leon": {
    "src": "/car-photos/seat-leon.jpg",
    "width": 640,
    "height": 313,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/SEAT_Le%C3%B3n",
    "sourcePageTitle": "SEAT León",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "seat-ibiza": {
    "src": "/car-photos/seat-ibiza.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/SEAT_Ibiza",
    "sourcePageTitle": "SEAT Ibiza",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "cupra-formentor": {
    "src": "/car-photos/cupra-formentor.jpg",
    "width": 640,
    "height": 347,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Cupra_Formentor",
    "sourcePageTitle": "Cupra Formentor",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "alfa-romeo-giulia": {
    "src": "/car-photos/alfa-romeo-giulia.jpg",
    "width": 640,
    "height": 452,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Alfa_Romeo_Giulia",
    "sourcePageTitle": "Alfa Romeo Giulia",
    "artist": "Kelebek",
    "license": "Public domain",
    "licenseUrl": null
  },
  "mercedes-benz-gla": {
    "src": "/car-photos/mercedes-benz-gla.jpg",
    "width": 640,
    "height": 344,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_GLA",
    "sourcePageTitle": "Mercedes-Benz GLA",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "mercedes-benz-glc": {
    "src": "/car-photos/mercedes-benz-glc.jpg",
    "width": 640,
    "height": 348,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_GLC",
    "sourcePageTitle": "Mercedes-Benz GLC",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-a-serisi": {
    "src": "/car-photos/mercedes-benz-a-serisi.jpg",
    "width": 640,
    "height": 303,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_A-Class",
    "sourcePageTitle": "Mercedes-Benz A-Class",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "bmw-x1": {
    "src": "/car-photos/bmw-x1.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BMW_X1",
    "sourcePageTitle": "BMW X1",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "bmw-x3": {
    "src": "/car-photos/bmw-x3.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BMW_X3",
    "sourcePageTitle": "BMW X3",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-q3": {
    "src": "/car-photos/audi-q3.jpg",
    "width": 640,
    "height": 428,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_Q3",
    "sourcePageTitle": "Audi Q3",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-q5": {
    "src": "/car-photos/audi-q5.jpg",
    "width": 640,
    "height": 362,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_Q5",
    "sourcePageTitle": "Audi Q5",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "jaguar-f-pace": {
    "src": "/car-photos/jaguar-f-pace.jpg",
    "width": 640,
    "height": 316,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Jaguar_F-Pace",
    "sourcePageTitle": "Jaguar F-Pace",
    "artist": "Charles01",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "land-rover-range-rover-evoque": {
    "src": "/car-photos/land-rover-range-rover-evoque.jpg",
    "width": 640,
    "height": 347,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Range_Rover_Evoque",
    "sourcePageTitle": "Range Rover Evoque",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "land-rover-range-rover-sport": {
    "src": "/car-photos/land-rover-range-rover-sport.jpg",
    "width": 640,
    "height": 338,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Range_Rover_Sport",
    "sourcePageTitle": "Range Rover Sport",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-land-cruiser": {
    "src": "/car-photos/toyota-land-cruiser.png",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Land_Cruiser",
    "sourcePageTitle": "Toyota Land Cruiser",
    "artist": "Autosdeprimera",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0"
  },
  "nissan-x-trail": {
    "src": "/car-photos/nissan-x-trail.jpg",
    "width": 640,
    "height": 347,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Nissan_X-Trail",
    "sourcePageTitle": "Nissan X-Trail",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "chery-tiggo-7-pro": {
    "src": "/car-photos/chery-tiggo-7-pro.jpg",
    "width": 640,
    "height": 384,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Chery_Tiggo_7",
    "sourcePageTitle": "Chery Tiggo 7",
    "artist": "JustAnotherCarDesigner",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "chery-tiggo-8-pro": {
    "src": "/car-photos/chery-tiggo-8-pro.jpg",
    "width": 640,
    "height": 384,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Chery_Tiggo_8",
    "sourcePageTitle": "Chery Tiggo 8",
    "artist": "JustAnotherCarDesigner",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en"
  },
  "omoda-5": {
    "src": "/car-photos/omoda-5.png",
    "width": 640,
    "height": 384,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Omoda_C5",
    "sourcePageTitle": "Omoda C5",
    "artist": "Autosdeprimera",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0"
  },
  "gwm-haval-jolion": {
    "src": "/car-photos/gwm-haval-jolion.jpg",
    "width": 640,
    "height": 375,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Haval_Jolion",
    "sourcePageTitle": "Haval Jolion",
    "artist": "User3204",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "jac-t8": {
    "src": "/car-photos/jac-t8.jpg",
    "width": 640,
    "height": 480,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/JAC_Shuailing_T8",
    "sourcePageTitle": "JAC Shuailing T8",
    "artist": "Jason Lawrence",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  "byd-han": {
    "src": "/car-photos/byd-han.jpg",
    "width": 640,
    "height": 293,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BYD_Han",
    "sourcePageTitle": "BYD Han",
    "artist": "Kevauto",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "togg-t10f": {
    "src": "/car-photos/togg-t10f.jpg",
    "width": 640,
    "height": 373,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Togg_T10F",
    "sourcePageTitle": "Togg T10F",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "ford-ranger": {
    "src": "/car-photos/ford-ranger.jpg",
    "width": 640,
    "height": 361,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Ranger",
    "sourcePageTitle": "Ford Ranger",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-hilux": {
    "src": "/car-photos/toyota-hilux.jpg",
    "width": 640,
    "height": 317,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Hilux",
    "sourcePageTitle": "Toyota Hilux",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "isuzu-d-max": {
    "src": "/car-photos/isuzu-d-max.jpg",
    "width": 640,
    "height": 367,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Isuzu_D-Max",
    "sourcePageTitle": "Isuzu D-Max",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-amarok": {
    "src": "/car-photos/volkswagen-amarok.jpg",
    "width": 640,
    "height": 340,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Amarok",
    "sourcePageTitle": "Volkswagen Amarok",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "mitsubishi-l200": {
    "src": "/car-photos/mitsubishi-l200.jpg",
    "width": 640,
    "height": 349,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mitsubishi_Triton",
    "sourcePageTitle": "Mitsubishi Triton",
    "artist": "Ethan Llamas",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "fiat-panda": {
    "src": "/car-photos/fiat-panda.jpg",
    "width": 640,
    "height": 382,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_Panda",
    "sourcePageTitle": "Fiat Panda",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "fiat-500x": {
    "src": "/car-photos/fiat-500x.jpg",
    "width": 640,
    "height": 357,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_500X",
    "sourcePageTitle": "Fiat 500X",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "fiat-500l": {
    "src": "/car-photos/fiat-500l.jpg",
    "width": 640,
    "height": 338,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Fiat_500L",
    "sourcePageTitle": "Fiat 500L",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-austral": {
    "src": "/car-photos/renault-austral.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Austral",
    "sourcePageTitle": "Renault Austral",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-symbioz": {
    "src": "/car-photos/renault-symbioz.jpg",
    "width": 640,
    "height": 382,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Symbioz",
    "sourcePageTitle": "Renault Symbioz",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-arkana": {
    "src": "/car-photos/renault-arkana.jpg",
    "width": 640,
    "height": 396,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Arkana",
    "sourcePageTitle": "Renault Arkana",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "renault-twingo": {
    "src": "/car-photos/renault-twingo.jpg",
    "width": 640,
    "height": 405,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Twingo",
    "sourcePageTitle": "Renault Twingo",
    "artist": "M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "renault-scenic": {
    "src": "/car-photos/renault-scenic.jpg",
    "width": 640,
    "height": 383,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Sc%C3%A9nic",
    "sourcePageTitle": "Renault Scénic",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-arteon": {
    "src": "/car-photos/volkswagen-arteon.jpg",
    "width": 640,
    "height": 309,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Arteon",
    "sourcePageTitle": "Volkswagen Arteon",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-taigo": {
    "src": "/car-photos/volkswagen-taigo.jpg",
    "width": 640,
    "height": 361,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Taigo",
    "sourcePageTitle": "Volkswagen Taigo",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-id-4": {
    "src": "/car-photos/volkswagen-id-4.jpg",
    "width": 640,
    "height": 356,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_ID.4",
    "sourcePageTitle": "Volkswagen ID.4",
    "artist": "LuvsMG481",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-id-3": {
    "src": "/car-photos/volkswagen-id-3.jpg",
    "width": 640,
    "height": 368,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_ID.3",
    "sourcePageTitle": "Volkswagen ID.3",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volkswagen-t-cross": {
    "src": "/car-photos/volkswagen-t-cross.jpg",
    "width": 640,
    "height": 364,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_T-Cross",
    "sourcePageTitle": "Volkswagen T-Cross",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "volkswagen-touareg": {
    "src": "/car-photos/volkswagen-touareg.jpg",
    "width": 640,
    "height": 341,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volkswagen_Touareg",
    "sourcePageTitle": "Volkswagen Touareg",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-aygo-x": {
    "src": "/car-photos/toyota-aygo-x.jpg",
    "width": 640,
    "height": 413,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Aygo_X",
    "sourcePageTitle": "Toyota Aygo X",
    "artist": "DieselFordMondeo",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-yaris-cross": {
    "src": "/car-photos/toyota-yaris-cross.jpg",
    "width": 640,
    "height": 368,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Yaris_Cross",
    "sourcePageTitle": "Toyota Yaris Cross",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-camry": {
    "src": "/car-photos/toyota-camry.jpg",
    "width": 640,
    "height": 279,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Camry",
    "sourcePageTitle": "Toyota Camry",
    "artist": "EurovisionNim",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-highlander": {
    "src": "/car-photos/toyota-highlander.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Highlander",
    "sourcePageTitle": "Toyota Highlander",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "toyota-corolla-cross": {
    "src": "/car-photos/toyota-corolla-cross.jpg",
    "width": 640,
    "height": 400,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Corolla_Cross",
    "sourcePageTitle": "Toyota Corolla Cross",
    "artist": "Mr.choppers",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0"
  },
  "toyota-prius": {
    "src": "/car-photos/toyota-prius.jpg",
    "width": 640,
    "height": 342,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Toyota_Prius",
    "sourcePageTitle": "Toyota Prius",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "hyundai-i10": {
    "src": "/car-photos/hyundai-i10.jpg",
    "width": 640,
    "height": 366,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_i10",
    "sourcePageTitle": "Hyundai i10",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "hyundai-i30": {
    "src": "/car-photos/hyundai-i30.jpg",
    "width": 640,
    "height": 322,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_i30",
    "sourcePageTitle": "Hyundai i30",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-creta": {
    "src": "/car-photos/hyundai-creta.jpg",
    "width": 640,
    "height": 375,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Creta",
    "sourcePageTitle": "Hyundai Creta",
    "artist": "RL GNZLZ",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0"
  },
  "hyundai-santa-fe": {
    "src": "/car-photos/hyundai-santa-fe.jpg",
    "width": 640,
    "height": 390,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Santa_Fe",
    "sourcePageTitle": "Hyundai Santa Fe",
    "artist": "Elise240SX",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "hyundai-ioniq-5": {
    "src": "/car-photos/hyundai-ioniq-5.jpg",
    "width": 640,
    "height": 328,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Ioniq_5",
    "sourcePageTitle": "Hyundai Ioniq 5",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "hyundai-accent": {
    "src": "/car-photos/hyundai-accent.jpg",
    "width": 640,
    "height": 319,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Hyundai_Accent",
    "sourcePageTitle": "Hyundai Accent",
    "artist": "Kevauto",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "ford-fiesta": {
    "src": "/car-photos/ford-fiesta.jpg",
    "width": 640,
    "height": 373,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Fiesta",
    "sourcePageTitle": "Ford Fiesta",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "ford-ecosport": {
    "src": "/car-photos/ford-ecosport.jpg",
    "width": 640,
    "height": 383,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_EcoSport",
    "sourcePageTitle": "Ford EcoSport",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "ford-kuga": {
    "src": "/car-photos/ford-kuga.jpg",
    "width": 640,
    "height": 350,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Kuga",
    "sourcePageTitle": "Ford Kuga",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "ford-bronco": {
    "src": "/car-photos/ford-bronco.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Ford_Bronco",
    "sourcePageTitle": "Ford Bronco",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "peugeot-508": {
    "src": "/car-photos/peugeot-508.jpg",
    "width": 640,
    "height": 291,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_508",
    "sourcePageTitle": "Peugeot 508",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "peugeot-408": {
    "src": "/car-photos/peugeot-408.jpg",
    "width": 640,
    "height": 339,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_408_(saloon)",
    "sourcePageTitle": "Peugeot 408 (saloon)",
    "artist": "Zotyefan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "peugeot-5008": {
    "src": "/car-photos/peugeot-5008.jpg",
    "width": 640,
    "height": 435,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_5008",
    "sourcePageTitle": "Peugeot 5008",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "peugeot-108": {
    "src": "/car-photos/peugeot-108.jpg",
    "width": 640,
    "height": 359,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Peugeot_108",
    "sourcePageTitle": "Peugeot 108",
    "artist": "Charles01",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "citroen-c3-aircross": {
    "src": "/car-photos/citroen-c3-aircross.jpg",
    "width": 640,
    "height": 391,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Citro%C3%ABn_C3_Aircross",
    "sourcePageTitle": "Citroën C3 Aircross",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "citroen-c4": {
    "src": "/car-photos/citroen-c4.jpg",
    "width": 640,
    "height": 337,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Citro%C3%ABn_C4",
    "sourcePageTitle": "Citroën C4",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "citroen-c5-aircross": {
    "src": "/car-photos/citroen-c5-aircross.jpg",
    "width": 640,
    "height": 389,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Citro%C3%ABn_C5_Aircross",
    "sourcePageTitle": "Citroën C5 Aircross",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "citroen-berlingo": {
    "src": "/car-photos/citroen-berlingo.jpg",
    "width": 640,
    "height": 361,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Citro%C3%ABn_Berlingo",
    "sourcePageTitle": "Citroën Berlingo",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "opel-grandland": {
    "src": "/car-photos/opel-grandland.jpg",
    "width": 640,
    "height": 374,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Opel_Grandland",
    "sourcePageTitle": "Opel Grandland",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "opel-insignia": {
    "src": "/car-photos/opel-insignia.jpg",
    "width": 640,
    "height": 300,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Opel_Insignia",
    "sourcePageTitle": "Opel Insignia",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "opel-crossland": {
    "src": "/car-photos/opel-crossland.jpg",
    "width": 640,
    "height": 399,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Opel_Crossland",
    "sourcePageTitle": "Opel Crossland",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "dacia-spring": {
    "src": "/car-photos/dacia-spring.png",
    "width": 640,
    "height": 384,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Renault_Kwid",
    "sourcePageTitle": "Renault Kwid",
    "artist": "Autosdeprimera",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0"
  },
  "dacia-bigster": {
    "src": "/car-photos/dacia-bigster.jpg",
    "width": 640,
    "height": 376,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Dacia_Bigster",
    "sourcePageTitle": "Dacia Bigster",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "skoda-kamiq": {
    "src": "/car-photos/skoda-kamiq.jpg",
    "width": 640,
    "height": 358,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Kamiq",
    "sourcePageTitle": "Škoda Kamiq",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "skoda-karoq": {
    "src": "/car-photos/skoda-karoq.jpg",
    "width": 640,
    "height": 354,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Karoq",
    "sourcePageTitle": "Škoda Karoq",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "skoda-kodiaq": {
    "src": "/car-photos/skoda-kodiaq.jpg",
    "width": 640,
    "height": 333,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Kodiaq",
    "sourcePageTitle": "Škoda Kodiaq",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "skoda-superb": {
    "src": "/car-photos/skoda-superb.jpg",
    "width": 640,
    "height": 313,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Superb",
    "sourcePageTitle": "Škoda Superb",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "skoda-enyaq": {
    "src": "/car-photos/skoda-enyaq.jpg",
    "width": 640,
    "height": 426,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/%C5%A0koda_Enyaq",
    "sourcePageTitle": "Škoda Enyaq",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-picanto": {
    "src": "/car-photos/kia-picanto.jpg",
    "width": 640,
    "height": 379,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Picanto",
    "sourcePageTitle": "Kia Picanto",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-rio": {
    "src": "/car-photos/kia-rio.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Rio",
    "sourcePageTitle": "Kia Rio",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-sorento": {
    "src": "/car-photos/kia-sorento.jpg",
    "width": 640,
    "height": 372,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Sorento",
    "sourcePageTitle": "Kia Sorento",
    "artist": "Kevauto",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-ev6": {
    "src": "/car-photos/kia-ev6.jpg",
    "width": 640,
    "height": 303,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_EV6",
    "sourcePageTitle": "Kia EV6",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-ev9": {
    "src": "/car-photos/kia-ev9.jpg",
    "width": 640,
    "height": 371,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_EV9",
    "sourcePageTitle": "Kia EV9",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "kia-seltos": {
    "src": "/car-photos/kia-seltos.jpg",
    "width": 640,
    "height": 357,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Kia_Seltos",
    "sourcePageTitle": "Kia Seltos",
    "artist": "Damian B Oh",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "nissan-micra": {
    "src": "/car-photos/nissan-micra.jpg",
    "width": 640,
    "height": 407,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Nissan_Micra",
    "sourcePageTitle": "Nissan Micra",
    "artist": "Elise240SX",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "nissan-leaf": {
    "src": "/car-photos/nissan-leaf.jpg",
    "width": 640,
    "height": 351,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Nissan_Leaf",
    "sourcePageTitle": "Nissan Leaf",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "nissan-navara": {
    "src": "/car-photos/nissan-navara.jpg",
    "width": 640,
    "height": 374,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Nissan_Navara",
    "sourcePageTitle": "Nissan Navara",
    "artist": "Vogue2Voke",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "honda-jazz": {
    "src": "/car-photos/honda-jazz.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Honda_Jazz",
    "sourcePageTitle": "Honda Jazz",
    "artist": "Niels de Wit from Lunteren, The Netherlands",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  "honda-hr-v": {
    "src": "/car-photos/honda-hr-v.jpg",
    "width": 640,
    "height": 367,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Honda_HR-V",
    "sourcePageTitle": "Honda HR-V",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "honda-city": {
    "src": "/car-photos/honda-city.jpg",
    "width": 640,
    "height": 384,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Honda_City",
    "sourcePageTitle": "Honda City",
    "artist": "Andra Febrian",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-e-serisi": {
    "src": "/car-photos/mercedes-benz-e-serisi.jpg",
    "width": 640,
    "height": 304,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_E-Class",
    "sourcePageTitle": "Mercedes-Benz E-Class",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-s-serisi": {
    "src": "/car-photos/mercedes-benz-s-serisi.jpg",
    "width": 640,
    "height": 282,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_S-Class",
    "sourcePageTitle": "Mercedes-Benz S-Class",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-gle": {
    "src": "/car-photos/mercedes-benz-gle.jpg",
    "width": 640,
    "height": 350,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_GLE",
    "sourcePageTitle": "Mercedes-Benz GLE",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "mercedes-benz-gls": {
    "src": "/car-photos/mercedes-benz-gls.jpg",
    "width": 640,
    "height": 332,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_GLS",
    "sourcePageTitle": "Mercedes-Benz GLS",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-eqa": {
    "src": "/car-photos/mercedes-benz-eqa.jpg",
    "width": 640,
    "height": 350,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_EQA",
    "sourcePageTitle": "Mercedes-Benz EQA",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mercedes-benz-cla": {
    "src": "/car-photos/mercedes-benz-cla.jpg",
    "width": 640,
    "height": 314,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mercedes-Benz_CLA",
    "sourcePageTitle": "Mercedes-Benz CLA",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-a1": {
    "src": "/car-photos/audi-a1.jpg",
    "width": 640,
    "height": 351,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_A1",
    "sourcePageTitle": "Audi A1",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-a4": {
    "src": "/car-photos/audi-a4.jpg",
    "width": 640,
    "height": 333,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_A4",
    "sourcePageTitle": "Audi A4",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-a6": {
    "src": "/car-photos/audi-a6.jpg",
    "width": 640,
    "height": 296,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_A6",
    "sourcePageTitle": "Audi A6",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-q7": {
    "src": "/car-photos/audi-q7.jpg",
    "width": 640,
    "height": 331,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_Q7",
    "sourcePageTitle": "Audi Q7",
    "artist": "Ethan Llamas",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "audi-e-tron": {
    "src": "/car-photos/audi-e-tron.jpg",
    "width": 640,
    "height": 355,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Audi_e-tron",
    "sourcePageTitle": "Audi e-tron",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volvo-xc60": {
    "src": "/car-photos/volvo-xc60.jpg",
    "width": 640,
    "height": 368,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volvo_XC60",
    "sourcePageTitle": "Volvo XC60",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volvo-xc90": {
    "src": "/car-photos/volvo-xc90.jpg",
    "width": 640,
    "height": 353,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volvo_XC90",
    "sourcePageTitle": "Volvo XC90",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "volvo-s60": {
    "src": "/car-photos/volvo-s60.jpg",
    "width": 640,
    "height": 357,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volvo_S60",
    "sourcePageTitle": "Volvo S60",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "volvo-ex30": {
    "src": "/car-photos/volvo-ex30.jpg",
    "width": 640,
    "height": 368,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Volvo_EX30",
    "sourcePageTitle": "Volvo EX30",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "land-rover-discovery-sport": {
    "src": "/car-photos/land-rover-discovery-sport.jpg",
    "width": 640,
    "height": 321,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Land_Rover_Discovery_Sport",
    "sourcePageTitle": "Land Rover Discovery Sport",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "land-rover-range-rover": {
    "src": "/car-photos/land-rover-range-rover.jpg",
    "width": 640,
    "height": 361,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Range_Rover",
    "sourcePageTitle": "Range Rover",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "land-rover-range-rover-velar": {
    "src": "/car-photos/land-rover-range-rover-velar.jpg",
    "width": 640,
    "height": 289,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Range_Rover_Velar",
    "sourcePageTitle": "Range Rover Velar",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "porsche-cayenne": {
    "src": "/car-photos/porsche-cayenne.jpg",
    "width": 640,
    "height": 333,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Porsche_Cayenne",
    "sourcePageTitle": "Porsche Cayenne",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "porsche-macan": {
    "src": "/car-photos/porsche-macan.jpg",
    "width": 640,
    "height": 426,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Porsche_Macan",
    "sourcePageTitle": "Porsche Macan",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "porsche-taycan": {
    "src": "/car-photos/porsche-taycan.jpg",
    "width": 640,
    "height": 276,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Porsche_Taycan",
    "sourcePageTitle": "Porsche Taycan",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "porsche-panamera": {
    "src": "/car-photos/porsche-panamera.jpg",
    "width": 640,
    "height": 426,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Porsche_Panamera",
    "sourcePageTitle": "Porsche Panamera",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mitsubishi-outlander": {
    "src": "/car-photos/mitsubishi-outlander.jpg",
    "width": 640,
    "height": 395,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mitsubishi_Outlander",
    "sourcePageTitle": "Mitsubishi Outlander",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mitsubishi-asx": {
    "src": "/car-photos/mitsubishi-asx.jpg",
    "width": 640,
    "height": 363,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mitsubishi_ASX",
    "sourcePageTitle": "Mitsubishi ASX",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mitsubishi-eclipse-cross": {
    "src": "/car-photos/mitsubishi-eclipse-cross.jpg",
    "width": 640,
    "height": 314,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mitsubishi_Eclipse_Cross",
    "sourcePageTitle": "Mitsubishi Eclipse Cross",
    "artist": "MercurySable99",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mitsubishi-xpander": {
    "src": "/car-photos/mitsubishi-xpander.jpg",
    "width": 640,
    "height": 380,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Mitsubishi_Xpander",
    "sourcePageTitle": "Mitsubishi Xpander",
    "artist": "オーバードライブ83",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "subaru-outback": {
    "src": "/car-photos/subaru-outback.jpg",
    "width": 640,
    "height": 428,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Subaru_Outback",
    "sourcePageTitle": "Subaru Outback",
    "artist": "MercurySable99",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "subaru-xv": {
    "src": "/car-photos/subaru-xv.jpg",
    "width": 640,
    "height": 350,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Subaru_Crosstrek",
    "sourcePageTitle": "Subaru Crosstrek",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "subaru-impreza": {
    "src": "/car-photos/subaru-impreza.jpg",
    "width": 640,
    "height": 345,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Subaru_Impreza",
    "sourcePageTitle": "Subaru Impreza",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "seat-arona": {
    "src": "/car-photos/seat-arona.jpg",
    "width": 640,
    "height": 347,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/SEAT_Arona",
    "sourcePageTitle": "SEAT Arona",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "seat-ateca": {
    "src": "/car-photos/seat-ateca.jpg",
    "width": 640,
    "height": 319,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/SEAT_Ateca",
    "sourcePageTitle": "SEAT Ateca",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "seat-tarraco": {
    "src": "/car-photos/seat-tarraco.jpg",
    "width": 640,
    "height": 313,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/SEAT_Tarraco",
    "sourcePageTitle": "SEAT Tarraco",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "cupra-born": {
    "src": "/car-photos/cupra-born.jpg",
    "width": 640,
    "height": 354,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Cupra_Born",
    "sourcePageTitle": "Cupra Born",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "cupra-tavascan": {
    "src": "/car-photos/cupra-tavascan.jpg",
    "width": 640,
    "height": 324,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Cupra_Tavascan",
    "sourcePageTitle": "Cupra Tavascan",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "cupra-terramar": {
    "src": "/car-photos/cupra-terramar.jpg",
    "width": 640,
    "height": 378,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Cupra_Terramar",
    "sourcePageTitle": "Cupra Terramar",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "alfa-romeo-stelvio": {
    "src": "/car-photos/alfa-romeo-stelvio.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Alfa_Romeo_Stelvio",
    "sourcePageTitle": "Alfa Romeo Stelvio",
    "artist": "Motor Verso",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0"
  },
  "alfa-romeo-tonale": {
    "src": "/car-photos/alfa-romeo-tonale.jpg",
    "width": 640,
    "height": 390,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Alfa_Romeo_Tonale",
    "sourcePageTitle": "Alfa Romeo Tonale",
    "artist": "Matthias v.d. Elbe",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0"
  },
  "alfa-romeo-giulietta": {
    "src": "/car-photos/alfa-romeo-giulietta.jpg",
    "width": 640,
    "height": 428,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Alfa_Romeo_Giulietta_(2010)",
    "sourcePageTitle": "Alfa Romeo Giulietta (2010)",
    "artist": "OSX",
    "license": "Public domain",
    "licenseUrl": null
  },
  "jaguar-e-pace": {
    "src": "/car-photos/jaguar-e-pace.jpg",
    "width": 640,
    "height": 350,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Jaguar_E-Pace",
    "sourcePageTitle": "Jaguar E-Pace",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "jaguar-f-type": {
    "src": "/car-photos/jaguar-f-type.jpg",
    "width": 640,
    "height": 302,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Jaguar_F-Type",
    "sourcePageTitle": "Jaguar F-Type",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "jaguar-i-pace": {
    "src": "/car-photos/jaguar-i-pace.jpg",
    "width": 640,
    "height": 322,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Jaguar_I-Pace",
    "sourcePageTitle": "Jaguar I-Pace",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mg-mg3": {
    "src": "/car-photos/mg-mg3.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/MG3_(automobile)",
    "sourcePageTitle": "MG3 (automobile)",
    "artist": "Alexander-93",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mg-mg5": {
    "src": "/car-photos/mg-mg5.jpg",
    "width": 640,
    "height": 319,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/MG5_(automobile)",
    "sourcePageTitle": "MG5 (automobile)",
    "artist": "User3204",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "mg-hs": {
    "src": "/car-photos/mg-hs.jpg",
    "width": 640,
    "height": 356,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/MG_HS",
    "sourcePageTitle": "MG HS",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "mg-mg4": {
    "src": "/car-photos/mg-mg4.jpg",
    "width": 640,
    "height": 328,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/MG4_EV",
    "sourcePageTitle": "MG4 EV",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "byd-atto-3": {
    "src": "/car-photos/byd-atto-3.jpg",
    "width": 640,
    "height": 348,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BYD_Atto_3",
    "sourcePageTitle": "BYD Atto 3",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "byd-dolphin": {
    "src": "/car-photos/byd-dolphin.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BYD_Dolphin",
    "sourcePageTitle": "BYD Dolphin",
    "artist": "User3204",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "byd-song": {
    "src": "/car-photos/byd-song.jpg",
    "width": 640,
    "height": 383,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BYD_Song",
    "sourcePageTitle": "BYD Song",
    "artist": "User3204",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "byd-tang": {
    "src": "/car-photos/byd-tang.jpg",
    "width": 640,
    "height": 427,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/BYD_Tang",
    "sourcePageTitle": "BYD Tang",
    "artist": "BYD Tang DM-p front quarter.jpg: Taylormilan3216\nderivative work: Mariordo (Mario Roberto Durán Ortiz)",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "tesla-model-y": {
    "src": "/car-photos/tesla-model-y.jpg",
    "width": 640,
    "height": 343,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Tesla_Model_Y",
    "sourcePageTitle": "Tesla Model Y",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "tesla-model-s": {
    "src": "/car-photos/tesla-model-s.jpg",
    "width": 640,
    "height": 317,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Tesla_Model_S",
    "sourcePageTitle": "Tesla Model S",
    "artist": "Peteratkins",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "tesla-model-x": {
    "src": "/car-photos/tesla-model-x.jpg",
    "width": 640,
    "height": 324,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Tesla_Model_X",
    "sourcePageTitle": "Tesla Model X",
    "artist": "Vauxford",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "isuzu-mu-x": {
    "src": "/car-photos/isuzu-mu-x.jpg",
    "width": 640,
    "height": 371,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Isuzu_MU-X",
    "sourcePageTitle": "Isuzu MU-X",
    "artist": "© M 93",
    "license": "CC BY-SA 3.0 de",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en"
  },
  "jac-js4": {
    "src": "/car-photos/jac-js4.jpg",
    "width": 640,
    "height": 480,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Sehol_X4",
    "sourcePageTitle": "Sehol X4",
    "artist": "JustAnotherCarDesigner",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "jac-js8": {
    "src": "/car-photos/jac-js8.jpg",
    "width": 640,
    "height": 480,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/JAC_X8",
    "sourcePageTitle": "JAC X8",
    "artist": "JustAnotherCarDesigner",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "omoda-7": {
    "src": "/car-photos/omoda-7.jpg",
    "width": 640,
    "height": 395,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Omoda_C7",
    "sourcePageTitle": "Omoda C7",
    "artist": "Alexander Migl",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "gwm-haval-h6": {
    "src": "/car-photos/gwm-haval-h6.jpg",
    "width": 640,
    "height": 360,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Haval_H6",
    "sourcePageTitle": "Haval H6",
    "artist": "Zotyefan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  },
  "gwm-haval-dargo": {
    "src": "/car-photos/gwm-haval-dargo.jpg",
    "width": 640,
    "height": 394,
    "sourcePageUrl": "https://en.wikipedia.org/wiki/Haval_Big_Dog",
    "sourcePageTitle": "Haval Big Dog",
    "artist": "User3204",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0"
  }
};
